### ISSUE TITLE
1.18 Support?

### ISSUE THREAD

**Issue by jpeterik12** [AmyMialeeMods/visible-barriers#1]
An update to 1.18 would be greatly appreciated.

**Comment by AmyMialee** [comment]
It'll get one once I get some more time, very busy recently.

**Comment by HauntedCorpse** [comment]
> An update to 1.18 would be greatly appreciated.

From what I can see, it looks like the mod works just fine on 1.18.1

**Comment by AmyMialee** [comment]
Sounds good, just use the 1.17 version for now. Whenever I update to 1.18 it'll probably have some content changes.

**Comment by AmyMialee** [comment]
done properly
