### ISSUE TITLE
Mod changes behavior of dxyz for markers

### ISSUE THREAD

**Issue by tryashtar** [AmyMialeeMods/visible-barriers#10]
This one had me questioning reality until I figured out what was happening, haha!

When this mod is installed, `dx`/`dy`/`dz` in selectors select more markers than they used to.

Very simple repro:
```
/summon marker 0 0 0
/say @e[type=marker,x=0,y=0,z=0,dx=0]
```

In vanilla, the marker is _not found_ due to [MC-88533](https://bugs.mojang.com/browse/MC-88533). Fabric with no mods matches this behavior. With this mod installed, the marker is found! Of course, I'm working on some insane project that depends on the vanilla behavior, so this correction I cannot abide! 🙃

[I think this is the responsible code?](https://github.com/AmyMialeeMods/visible-barriers/blob/449edd7e6ba86d34f66be56c858254634eb0a6b4/src/main/java/amymialee/visiblebarriers/mixin/entities/EntityTypeMixin.java#L26) I don't really understand the motivation for that line; is it needed for the marker to be visible on the client? Or maybe you were trying specifically to fix the vanilla selector behavior.

**Comment by tryashtar** [comment]
Okay I just realized the easiest way to see this is just F3+B, and that may also be the reason for that line

**Comment by AmyMialee** [comment]
yea it's probably that minimum dimensions part since without that it's hard to make them render on client.
I'll try find some other way to get them to render, for now are you able to make a custom build without that? if not I could do it.

**Comment by tryashtar** [comment]
I'll give it a try
