### ISSUE TITLE
visible entities

### ISSUE THREAD

**Issue by MelonHell** [AmyMialeeMods/visible-barriers#11]
it would be convenient if the entities were visible as in the spectator, then what is now does not allow us to understand what position the same armorstand is in

**Comment by AmyMialee** [comment]
i don't really know what you mean

**Comment by MelonHell** [comment]
> i don't really know what you mean

something like this

```java
    @Inject(method = "isInvisible", at = @At("HEAD"), cancellable = true)
    public void isInvisible(CallbackInfoReturnable<Boolean> cir) {
        if (VisibleBarriers.isVisible()) cir.setReturnValue(false);
    }
```
