### ISSUE TITLE
Proximity option

### ISSUE THREAD

**Issue by Madis0** [AmyMialeeMods/visible-barriers#13]
How about a proximity option, aka the blocks will become visible when the player is, say, 5 blocks near.

**Comment by AmyMialee** [comment]
Not possible with how the mod works at the moment, as the model is reloaded to activate it.
If we did this we would need to do the model refresh every time you moved by a BlockPos, which would be unpleasant as heck, you can see what it'd be like by pressing the keybind repeatedly while walking.

If the mod was coded using a method that would be more compatible like particles this would be a nice idea though, it's just not feasible as it is right now.
