### ISSUE TITLE
Crash on startup (1.19.3)

### ISSUE THREAD

**Issue by Deliphin** [AmyMialeeMods/visible-barriers#15]
I added this to my pack and found it made the game unable to start. so I tried the mod in a new nigh-empty modpack and found the same results.

All the following crashlogs are on:
Java 17.0.5_8 (Installed from Ninite who uses AdoptOpenJDK, so Temurin I believe.)
Minecraft 1.19.3
LWJGL 3.3.1
`visible-barriers-1.5.3+1.19.x.jar`
`modmenu-5.0.2.jar`
`qfapi-5.0.0-alpha.8_qsl-4.0.0-beta.4_fapi-0.71.0_mc-1.19.3.jar`

[crash-2023-01-06_18.39.44-client.txt](https://github.com/AmyMialeeMods/visible-barriers/files/10363633/crash-2023-01-06_18.39.44-client.txt)
With Quilt Loader 0.17.8 (current stable)

[crash-2023-01-06_18.43.50-client.txt](https://github.com/AmyMialeeMods/visible-barriers/files/10363634/crash-2023-01-06_18.43.50-client.txt)
With Quilt Loader 0.18.1-beta.27 (current newest)

[crash-2023-01-06_18.46.07-client.txt](https://github.com/AmyMialeeMods/visible-barriers/files/10363639/crash-2023-01-06_18.46.07-client.txt)
With Quilt Loader 0.18.1-beta.27, and replacing QFAPI with Fabric API 0.71.0+1.19.3

[crash-2023-01-06_18.47.46-client.txt](https://github.com/AmyMialeeMods/visible-barriers/files/10363644/crash-2023-01-06_18.47.46-client.txt)
With Fabric Loader 0.14.12 and Fabric API 0.71.0+1.19.3

**Comment by AmyMialee** [comment]
Yea sorry about that, I've been meaning to publish the last 1.19.2 update
before updating to 1.19.3 but I haven't gotten to that yet.

**Comment by RedVortexDev** [comment]
1.19.x is kind of missleading

**Comment by AmyMialee** [comment]
Well I mean yea it wasn't misleading at the time.

**Comment by SteadyStatus21** [comment]
Hey @AmyMialee! Thank you for creating this mod! Do you have a timeframe when the 1.19.3 release might come out? I am not trying to rush you, but to get a understanding as I am staying on 1.19.2 right now. 

Thanks,
SteadyStatus21

**Comment by AmyMialee** [comment]
I'm not quite sure, but if you're in need I think someone made a port in a pr, so you could build from that.

I haven't pulled it in yet as new features were added since the version it was made for and I'd like the full release to be feature complete.

**Comment by AmyMialee** [comment]
I'm not quite sure, but if you're in need I think someone made a port in a pr, so you could build from that.

I haven't pulled it in yet as new features were added since the version it was made for and I'd like the full release to be feature complete.

**Comment by AmyMialee** [comment]
Sorry forgot to mention, its been released.
