### ISSUE TITLE
[Bug] Most particles not rendering

### ISSUE THREAD

**Issue by RandomGgames** [AmyMialeeMods/visible-barriers#17]
Having this mod installed along with my other mods stops particles from rendering. Uninstalling it allows particles to render again. 

Mod version: visible-barriers-1.7.0
Game version: 1.19.3
Other mods installed:
- 3dskinlayers-fabric-1.5.2-mc1.19.3.jar
- accurate-block-placement-1.0.16.jar
- advancementinfo-1.19.3-fabric0.68.1-1.3.1.jar
- appleskin-fabric-mc1.19.3-2.4.2.jar
- bettermounthud-1.2.1.jar
- betterstats-2.2.2+1.19.3.jar
- Boat-Item-View-Fabric-1.19.3-0.0.4.jar
- bobby-4.0.3.jar
- cherishedworlds-fabric-6.0.2+1.19.3.jar
- Chunky-1.3.53.jar
- clickthrough-1.19.3-fabric0.68.1-0.4.jar
- cloth-config-9.0.94-fabric.jar
- Couplings-1.9.2+1.19.3.jar
- CreativeOnePunch-1.3-universal.jar
- dark-loading-screen-1.6.13.jar
- deepslatecutting-fabric-1.6.0.jar
- easiervillagertrading-1.19.3-fabric0.68.1-1.5.4.jar
- eating-animation-1.9.1.jar
- EditSign-1.19.3-2.7.0.jar
- Essential-fabric_1-19.jar
- fabric-api-0.75.1+1.19.3.jar
- fabric-carpet-1.19.3-1.4.96+v230201.jar
- fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
- fallingleaves-1.14.5+1.19.3.jar
- FallingTree-1.19.3-3.11.2.jar
- graves-2.2.0+1.19.3.jar
- grid-1.19.3-fabric0.68.1-1.6.7.jar
- horse-stats-vanilla-4.2.2.jar
- image2map-0.4.0.jar
- InventoryProfilesNext-fabric-1.19.3-1.9.2.jar
- iris-mc1.19.3-1.5.2.jar
- isometric-renders-0.4.3+1.19.3.jar
- jamlib-0.6.0+1.19.3.jar
- lambdynamiclights-2.2.0+1.19.3.jar
- letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar
- libIPN-fabric-1.19.3-2.0.2.jar
- list_files.py
- litematica-fabric-1.19.3-0.13.1.jar
- litematica-printer-1.19.3-3.1.jar
- lithium-fabric-mc1.19.3-0.10.4.jar
- malilib-fabric-1.19.3-0.14.0.jar
- minihud-fabric-1.19.3-0.25.0.jar
- modmenu-5.1.0-beta.4.jar
- NoChatReports-FABRIC-1.19.3-v2.0.0.jar
- notenoughanimations-fabric-1.6.2-mc1.19.3.jar
- owo-lib-0.10.2+1.19.3.jar
- PresenceFootsteps-1.7.1.jar
- reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
- right-click-harvest-3.1.0+1.19.3.jar
- slimyfloor-1.19.1-1.2.5.jar
- smoothboot-fabric-1.19-1.7.1.jar
- sodium-extra-0.4.17+mc1.19.3-build.95.jar
- sodium-fabric-mc1.19.3-0.4.9+build.23.jar
- starlight-1.1.1+fabric.ae22326.jar
- status-effect-bars-1.0.2.jar
- syncmatica-1.18.2-0.3.8.jar
- tweakeroo-fabric-1.19.3-0.15.0.jar
- vt-downloader-2.0.2.jar
- worldedit-mod-7.2.13.jar
- XaerosWorldMap_1.28.9_Fabric_1.19.3.jar
- Xaeros_Minimap_23.1.0_Fabric_1.19.3.jar

**Comment by AmyMialee** [comment]
which particles

**Comment by RandomGgames** [comment]
Some of the few I've noticed:
- [ ] Portal particles
- [ ] Torch fire
- [ ] Torch smoke
- [ ] Underwater ambient particles
- [ ] Bubble columns

**Comment by AmyMialee** [comment]
Ok turns out the thing removing barrier particles is removing all particles
to toggle just use /visiblebarriers hiddenparticles
