### ISSUE TITLE
Trapped Chests Suggestion

### ISSUE THREAD

**Issue by ghost** [AmyMialeeMods/visible-barriers#21]
It would be cool if you could easily see trapped chests with the mod on.
You could also add the new suspicious sand/gravel and maybe even powdered snow.

**Comment by IcyBlizzardPengu** [comment]
Oh and maybe powdered snow.

**Comment by CapToad** [comment]
just get a texture pack lol

**Comment by AmyMialee** [comment]
all of these already look different, it wouldn't make sense for this mod to make them simply more visible.
i do consider doing it for waxed copper and infested blocks as those look identical though
