### ISSUE TITLE
Add infested-block's visibility

### ISSUE THREAD

**Issue by SkyWors** [AmyMialeeMods/visible-barriers#4]
One block that would be nice to be able to display are infested blocks with, for example, a silverfish head texture on the block.

What do you think of this?

And petrified block. hummm...

**Comment by AmyMialee** [comment]
Great idea, now added
![2022-07-13_00 07 25](https://user-images.githubusercontent.com/10999535/178613298-f08f2fc8-94a4-48ad-b9bb-00be593ca07f.png)
![2022-07-13_00 07 27](https://user-images.githubusercontent.com/10999535/178613302-8dfb20cc-e990-4dc4-8f98-fc598984fbc4.png)

**Comment by AmyMialee** [comment]
![2022-07-12_23 55 11](https://user-images.githubusercontent.com/10999535/178613355-15f3ee3d-d2f3-4fc9-9814-91cb48dbc55b.png)
