### ISSUE TITLE
[Suggestion] Disable vanilla visibility toggle

### ISSUE THREAD

**Issue by StrideyGH** [AmyMialeeMods/visible-barriers#6]
Hey, this mod is extremely useful!
I was wondering if you'd be interested in adding a toggle in the config that allows toggling vanilla's method of showing barriers and light blocks when held, so that you can only see them when Visible Barriers is enabled. 
Thanks :)

**Comment by AmyMialee** [comment]
I don't know how I overlooked this, that's a really good idea!
It tends to get quite annoying when I toggle and the particles are in the way by accident.

I just need to find a good method of doing a config for it.

**Comment by AmyMialee** [comment]
Added, it has a config option and a command.
