### ISSUE TITLE
Add Support for Moving Piston

### ISSUE THREAD

**Issue by themdlchemist** [AmyMialeeMods/visible-barriers#9]
Moving Piston is the block used to represent a block that is currently being pushed by a piston. However, when you setblock a moving piston, it doesn't have any data on what block it is, and it renders invisible and has interesting properties for mapmaking and many technical uses. As such, I think that it would fit well with the other blocks that this mod makes visible.

**Comment by AmyMialee** [comment]
good idea! I may do this in future

**Comment by AmyMialee** [comment]
![image](https://user-images.githubusercontent.com/10999535/208249214-985155e9-eac6-4328-aafe-74abf97b906b.png)
